server:
  port: 8089
#  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    password: root
    username: root
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath*:mapper/*.xml